services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-man
    environment:
      MYSQL_ROOT_PASSWORD: localhost
      MYSQL_DATABASE: telcoservice
    ports:
      - "10000:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  spring-application:
    image: shivu2002/telcoservice-backend:v1.3
    container_name: telcoservice-spring-app
    # depends_on:
    #   - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/telcoservice?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Localhost3306
      REACT_ORIGIN: http://localhost:3000
      SPRING_MAIL_PASSWORD: your-password
    ports:
      - "8082:8082"
    networks:
      - app-network
    restart: on-failure

  react-application:
    image: shivu2002/telcoservice-frontend:v1.5
    container_name: telcoservice-react-app
    depends_on:
      - spring-application
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8082
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge
